### ISSUE TITLE
Memcache is broken

### ISSUE THREAD

**Issue by jonathanjfshaw** [wunderio/drupal-project-k8s#94]
## Problem
Enable memcache and use is as Drupal's default cache.
View a node.
Make a change to a node.
View the node.
Make another change to the node.
View the node.
Refresh the page.
Refresh the page.
Refresh the page.

Each time you refresh the page you will see at random one of the last 3 versions of the node.

## Cause
The default replica count of the Memcached chart is 3, and it has no router.
But the code in silta.settings.php tells Drupal's memcached that it is working with a single Memcached server, not 3.
```
if (getenv('MEMCACHED_HOST')) {
  $settings['memcache']['servers'] = [getenv('MEMCACHED_HOST') . ':11211' => 'default'];
}
```
Therefore I think it is querying the memcached service to access the cache, and getting redirected to a random memcached server/pod, hence displaying one of the last 3 versions at random

## Solution
Either
1) Use a script to discover the IP's of the memcached servers and set them all explicitly in silta.settings.php
2) Use a router. Mcrouter seems most popular (https://github.com/helm/charts/tree/master/stable/mcrouter) but there are alternatives like https://github.com/ianlewis/memcached-operator

See https://cloud.google.com/solutions/deploying-memcached-on-kubernetes-engine for some relevant docs (notice the way the example python memcached client is discovering the ips of all the memcached pods, not just talking only to the memcached service).

@Jancis did the original memcached PR.

(P.S. While I remember: there's a bug in values.yml
```
memcached:
 maxItemMemory: 128
```
should be
```
memcached:
  memcached:
    maxItemMemory: 128
```
See here https://github.com/helm/charts/blob/master/stable/memcached/values.yaml

**Comment by jonathanjfshaw** [comment]
I'm working around it for now by setting memcached.replicaCount=1. This gives me confidence my diagnosis is on the right lines.

**Comment by Jancis** [comment]
Limiting the replicaCount to 1 seems like the easiest solution right now.
