### ISSUE TITLE
File upload max size

### ISSUE THREAD

**Issue by jonathanjfshaw** [wunderio/drupal-project-k8s#95]
Current approach to controlling file upload max size has 2 problems:

1) there's a value in the php section of the values file, but it doesn't affect the nginx client_max_body_size parameter which is also relevant

2) the current nginx client_max_body_size does not apply when using an https ingress, resulting in the default nginx 1m limit applying. 
I'm currently working around this with annotations
```
    nginx.ingress.kubernetes.io/proxy-body-size: "60m"
    ingress.kubernetes.io/proxy-body-size: "60m"
```
but googling suggests it may also be possible to fix it by putting the `client_max_body_size` under `server` as well as under `http` in the nginx config.

**Comment by Jancis** [comment]
Fixed with https://github.com/wunderio/drupal-project-k8s/commit/806f6183cb9f5f5bc7d81ac5c64ec33912961039
